### ISSUE TITLE
RC for Postgres historian

### ISSUE THREAD

**Issue by shwethanidd** [eclipse-volttron/volttron-postgresql-historian#1]

**Comment by Bowriverstudio** [comment]
I'd like to test this when it is appropriate.

**Comment by craigpnnl** [comment]
@Bowriverstudio make sure you watch the repository so you can get notified when changes are made!

**Comment by jhaack** [comment]
Excellent, thanks

**Comment by craigpnnl** [comment]
@Bowriverstudio this is ready for you to test.
